
/* ⚠️ 自動產生，請勿手改
 * 來源：slots.list
 */
#ifndef SLOTS_H
#define SLOTS_H

#define IDX_CONST_2P32M1         0
#define IDX_CONST_2P30M1         1
#define IDX_CONST_2P30M19        2
#define IDX_CONST_2P15M1         3
#define IDX_CONST_2P20           4
#define IDX_CONST_2P41           5
#define IDX_CONST_2P62           6
#define IDX_CONST_2P20A2P41      7
#define IDX_X0                   8
#define IDX_X1                   9
#define IDX_X2                   10
#define IDX_X3                   11
#define IDX_INV0                 12
#define IDX_INV1                 13
#define IDX_INV2                 14
#define IDX_INV3                 15
#define IDX_VEC_F0               16
#define IDX_VEC_F1               17
#define IDX_VEC_F2               18
#define IDX_VEC_F3               19
#define IDX_VEC_F4               20
#define IDX_VEC_F5               21
#define IDX_VEC_F6               22
#define IDX_VEC_F7               23
#define IDX_VEC_F8               24
#define IDX_VEC_G0               25
#define IDX_VEC_G1               26
#define IDX_VEC_G2               27
#define IDX_VEC_G3               28
#define IDX_VEC_G4               29
#define IDX_VEC_G5               30
#define IDX_VEC_G6               31
#define IDX_VEC_G7               32
#define IDX_VEC_G8               33
#define IDX_VEC_V0               34
#define IDX_VEC_V1               35
#define IDX_VEC_V2               36
#define IDX_VEC_V3               37
#define IDX_VEC_V4               38
#define IDX_VEC_V5               39
#define IDX_VEC_V6               40
#define IDX_VEC_V7               41
#define IDX_VEC_V8               42
#define IDX_VEC_S0               43
#define IDX_VEC_S1               44
#define IDX_VEC_S2               45
#define IDX_VEC_S3               46
#define IDX_VEC_S4               47
#define IDX_VEC_S5               48
#define IDX_VEC_S6               49
#define IDX_VEC_S7               50
#define IDX_VEC_S8               51
#define IDX_DELTA                52
#define IDX_UU                   53
#define IDX_VV                   54
#define IDX_RR                   55
#define IDX_SS                   56
#define IDX_f                    57
#define IDX_g                    58
#define IDX_FUV                  59
#define IDX_GRS                  60
#define IDX_SCR0                 61
#define IDX_SCR1                 62
#define IDX_SCR2                 63
#define IDX_SCR3                 64
#define IDX_G0AND1               65
#define IDX_COND                 66
#define IDX_CMASK                67
#define IDX_NMASK                68
#define IDX_NEG_FUV              69
#define IDX_DELTA_SWAP           70
#define IDX_TMP                  71
#define IDX_u                    72
#define IDX_v                    73
#define IDX_r                    74
#define IDX_s                    75

/* Byte offsets (64-bit array → bytes) */
#define BYTE_IDX_CONST_2P32M1    0
#define BYTE_IDX_CONST_2P30M1    8
#define BYTE_IDX_CONST_2P30M19   16
#define BYTE_IDX_CONST_2P15M1    24
#define BYTE_IDX_CONST_2P20      32
#define BYTE_IDX_CONST_2P41      40
#define BYTE_IDX_CONST_2P62      48
#define BYTE_IDX_CONST_2P20A2P41 56
#define BYTE_IDX_X0              64
#define BYTE_IDX_X1              72
#define BYTE_IDX_X2              80
#define BYTE_IDX_X3              88
#define BYTE_IDX_INV0            96
#define BYTE_IDX_INV1            104
#define BYTE_IDX_INV2            112
#define BYTE_IDX_INV3            120
#define BYTE_IDX_VEC_F0          128
#define BYTE_IDX_VEC_F1          136
#define BYTE_IDX_VEC_F2          144
#define BYTE_IDX_VEC_F3          152
#define BYTE_IDX_VEC_F4          160
#define BYTE_IDX_VEC_F5          168
#define BYTE_IDX_VEC_F6          176
#define BYTE_IDX_VEC_F7          184
#define BYTE_IDX_VEC_F8          192
#define BYTE_IDX_VEC_G0          200
#define BYTE_IDX_VEC_G1          208
#define BYTE_IDX_VEC_G2          216
#define BYTE_IDX_VEC_G3          224
#define BYTE_IDX_VEC_G4          232
#define BYTE_IDX_VEC_G5          240
#define BYTE_IDX_VEC_G6          248
#define BYTE_IDX_VEC_G7          256
#define BYTE_IDX_VEC_G8          264
#define BYTE_IDX_VEC_V0          272
#define BYTE_IDX_VEC_V1          280
#define BYTE_IDX_VEC_V2          288
#define BYTE_IDX_VEC_V3          296
#define BYTE_IDX_VEC_V4          304
#define BYTE_IDX_VEC_V5          312
#define BYTE_IDX_VEC_V6          320
#define BYTE_IDX_VEC_V7          328
#define BYTE_IDX_VEC_V8          336
#define BYTE_IDX_VEC_S0          344
#define BYTE_IDX_VEC_S1          352
#define BYTE_IDX_VEC_S2          360
#define BYTE_IDX_VEC_S3          368
#define BYTE_IDX_VEC_S4          376
#define BYTE_IDX_VEC_S5          384
#define BYTE_IDX_VEC_S6          392
#define BYTE_IDX_VEC_S7          400
#define BYTE_IDX_VEC_S8          408
#define BYTE_IDX_DELTA           416
#define BYTE_IDX_UU              424
#define BYTE_IDX_VV              432
#define BYTE_IDX_RR              440
#define BYTE_IDX_SS              448
#define BYTE_IDX_f               456
#define BYTE_IDX_g               464
#define BYTE_IDX_FUV             472
#define BYTE_IDX_GRS             480
#define BYTE_IDX_SCR0            488
#define BYTE_IDX_SCR1            496
#define BYTE_IDX_SCR2            504
#define BYTE_IDX_SCR3            512
#define BYTE_IDX_G0AND1          520
#define BYTE_IDX_COND            528
#define BYTE_IDX_CMASK           536
#define BYTE_IDX_NMASK           544
#define BYTE_IDX_NEG_FUV         552
#define BYTE_IDX_DELTA_SWAP      560
#define BYTE_IDX_TMP             568
#define BYTE_IDX_u               576
#define BYTE_IDX_v               584
#define BYTE_IDX_r               592
#define BYTE_IDX_s               600

#define SLOTS_TOTAL               76
#define SLOT_OFFSET(idx)        ((idx) << 3)  /* 64-bit array -> bytes */

#endif /* SLOTS_H */
